version: "3"
virtualmachines:
- name: es3-api
  image: elastic/es3-api-v2
  shell: /bin/bash
  environment:
    PRODUCT_TIER: complete
    PROJECT_TYPE: observability
    REGIONS: aws-us-east-1
  memory: 12288
  cpus: 4
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: LLM_PROXY_PROD
- name: ESS_CLOUD_API_KEY
